#!/usr/bin/env python

import rospy
import numpy as np

from IPython import embed

from chugg_physics.ROSChuggSimulator import ROSChuggSimulator


if __name__=='__main__':
    rospy.init_node('chugg_simulator')

    sim = ROSChuggSimulator()

    def setWheelAcc(acc):
        sim.setWheelAcc(acc)
    def setExternalTorque(torque):
        sim.setExternalTorque(torque)
    def setState(*args, **kwargs):
        sim.setState(*args, **kwargs)

    embed()
    rospy.signal_shutdown('')
    
