#!/usr/bin/env python

import numpy as np

import chugg_learning.rbf_experiment as rbf_exp
from chugg_learning.simulator_domain import OfflineChuggSimulatorDomain

param_space = rbf_exp.param_space
make_experiment = rbf_exp.make_make_experiment(OfflineChuggSimulatorDomain)

if __name__ == '__main__':
    id = int(np.random.rand()*200)
    experiment = make_experiment(1)
    experiment.run()
    experiment.plot()
    # experiment.save()
