#!/usr/bin/env python

import rospy

import chugg_learning.rbf_experiment as rbf_exp
from chugg_learning.simulator_1d_domain import OfflineChuggSimulator1DDomain

param_space = rbf_exp.param_space
make_experiment = rbf_exp.make_make_experiment(OfflineChuggSimulator1DDomain)

if __name__ == '__main__':
   experiment = make_experiment(1)
   experiment.run(visualize_performance=1)
   experiment.plot()